<a href="https://colab.research.google.com/github/Piyushtatrari/CODE/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
 import numpy as np

In [ ]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]

In [ ]:
type(lst)

list

In [ ]:
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [ ]:
arr=np.array([1,24,4])

In [ ]:
arr

array([ 1, 24,  4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
zeros=np.zeros((5,3))

In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one =np.ones((3,4))

In [ ]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr=np.random.random((3,3))

array([[0.70306901, 0.04181385, 0.08555961],
       [0.73495263, 0.19578642, 0.69510494],
       [0.64022763, 0.0142686 , 0.03479793]])

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
np.linspace(1,7,11)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. ])

In [ ]:
arr = np.random.random((4,3))

In [ ]:
arr

array([[0.30682181, 0.75522352, 0.56225532],
       [0.00555569, 0.55449447, 0.54852449],
       [0.65272139, 0.95046739, 0.53920175],
       [0.30462891, 0.37569485, 0.42529767]])

In [ ]:
arr= np.reshape(arr,(3,4))

In [ ]:
arr

array([[0.30682181, 0.75522352, 0.56225532, 0.00555569],
       [0.55449447, 0.54852449, 0.65272139, 0.95046739],
       [0.53920175, 0.30462891, 0.37569485, 0.42529767]])

In [ ]:
arr.flatten()

array([0.30682181, 0.75522352, 0.56225532, 0.00555569, 0.55449447,
       0.54852449, 0.65272139, 0.95046739, 0.53920175, 0.30462891,
       0.37569485, 0.42529767])

In [ ]:
arr= np.array([[7,3,8,6,4],[7,2,9,8,6],[5,4,2,3,1]])

In [ ]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [ ]:
np.sort(arr, axis=0,kind="mergesort")

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [ ]:
np.sort(arr, axis=1,kind="mergesort")

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [ ]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
arr=np.column_stack((arr1,arr2))

In [ ]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [ ]:
arr=np.concatenate((arr1,arr2), axis = 0)

In [ ]:
np.concatenate((arr1,arr2.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [ ]:
np.transpose(arr)

array([[1, 5, 8, 4],
       [2, 6, 7, 3],
       [3, 7, 6, 2],
       [4, 8, 5, 1]])

In [ ]:
np.sort(arr,axis=1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
a[1::2]

array([ 2,  4,  6,  8, 10])